import { Asset } from "@/types";
import { MOCK_DEPARTMENTS } from "./mockData";

export const MOCK_ASSETS: Asset[] = [
  {
    id: "ast-001",
    assetTag: "ASSET-CSE-104",
    name: "Dell Latitude 5420 Laptop",
    category: "LAPTOP",
    condition: "GOOD",
    departmentId: "dept-cse",
    department: MOCK_DEPARTMENTS[0],
    location: { lat: 20.2482, lng: 85.8005, building: "ITER Academic Block 1 (CSE Complex)", floor: "3rd Floor", room: "AI & ML Lab 304" },
    ageYears: 2.2,
    purchaseDate: "2022-04-15",
    originalPrice: 82000,
    estimatedValue: 48000,
    estimatedRepairCost: 3500,
    status: "AVAILABLE",
    dataWipeRequired: true,
    dataWipeCompleted: true,
    recommendedAction: "REDISTRIBUTE",
    actionConfidence: 0.94,
    aiReasoning: "Hardware diagnostics indicate 11th Gen i7 CPU and 16GB RAM are in excellent operational condition. Battery health is at 78% (sufficient for desk usage). High demand in ITER Design & Innovation Studio (Block 6).",
    serialNumber: "DL5420-9842-XJ",
    manufacturer: "Dell Inc.",
    modelNumber: "Latitude 5420 vPro",
    specifications: { processor: "Intel Core i7-1185G7", ram: "16 GB DDR4", storage: "512 GB NVMe SSD", display: "14-inch FHD IPS" },
    tags: ["ITER CSIT", "Portable", "vPro", "IT Surplus"],
    createdAt: "2024-08-10T09:30:00Z",
    updatedAt: "2024-08-18T14:20:00Z",
  },
  {
    id: "ast-002",
    assetTag: "ASSET-ECE-302",
    name: "BenQ PD2700U 27-inch 4K Color Monitor",
    category: "MONITOR",
    condition: "EXCELLENT",
    departmentId: "dept-ece",
    department: MOCK_DEPARTMENTS[2],
    location: { lat: 20.2478, lng: 85.8015, building: "ITER Academic Block 4 (ECE)", floor: "2nd Floor", room: "DSP & Embedded Lab 202" },
    ageYears: 1.5,
    purchaseDate: "2023-01-20",
    originalPrice: 42000,
    estimatedValue: 31000,
    estimatedRepairCost: 0,
    status: "AVAILABLE",
    dataWipeRequired: false,
    dataWipeCompleted: false,
    recommendedAction: "REDISTRIBUTE",
    actionConfidence: 0.98,
    aiReasoning: "100% sRGB color calibration intact, zero dead pixels, full stand adjustment working. Immediate candidate for ITER Design Lab shortages.",
    serialNumber: "BQ27-88192-AU",
    manufacturer: "BenQ",
    modelNumber: "PD2700U Designer Monitor",
    specifications: { resolution: "3840 x 2160 (4K UHD)", panel: "IPS 10-bit", colorGamut: "100% sRGB / Rec.709", ports: "HDMI 2.0, DP 1.4, Mini DP" },
    tags: ["Color Accurate", "4K", "ITER ECE Ready"],
    createdAt: "2024-08-12T11:15:00Z",
    updatedAt: "2024-08-19T10:00:00Z",
  },
  {
    id: "ast-003",
    assetTag: "ASSET-LIB-082",
    name: "Herman Miller Aeron Ergonomic Chair (Size B)",
    category: "CHAIR",
    condition: "GOOD",
    departmentId: "dept-library",
    department: MOCK_DEPARTMENTS[5],
    location: { lat: 20.2472, lng: 85.8010, building: "ITER Biju Patnaik Central Library", floor: "2nd Floor", room: "Digital Reference Wing" },
    ageYears: 3.5,
    purchaseDate: "2021-02-10",
    originalPrice: 95000,
    estimatedValue: 52000,
    estimatedRepairCost: 1200,
    status: "AVAILABLE",
    dataWipeRequired: false,
    dataWipeCompleted: false,
    recommendedAction: "REUSE",
    actionConfidence: 0.96,
    aiReasoning: "Pellicle mesh suspension and PostureFit SL lumbar support are in top tier functional state. Minor castor wheel lubrication required.",
    serialNumber: "HM-AER-2021-883",
    manufacturer: "Herman Miller",
    modelNumber: "Aeron Mineral Fully Loaded",
    specifications: { size: "Size B (Medium)", adjustment: "Forward Tilt, Tilt Limiter, Fully Adj Arms", material: "8Z Pellicle Mesh" },
    tags: ["Ergonomic", "Central Library", "High Value"],
    createdAt: "2024-08-01T14:00:00Z",
    updatedAt: "2024-08-15T09:30:00Z",
  },
  {
    id: "ast-004",
    assetTag: "ASSET-ADM-044",
    name: "Epson EB-2250U Full HD Interactive Projector",
    category: "PROJECTOR",
    condition: "FAIR",
    departmentId: "dept-admin",
    department: MOCK_DEPARTMENTS[6],
    location: { lat: 20.2458, lng: 85.8015, building: "SOA Administrative Bhavan", floor: "Ground Floor", room: "Main Syndicate Room" },
    ageYears: 4.0,
    purchaseDate: "2020-09-18",
    originalPrice: 110000,
    estimatedValue: 40000,
    estimatedRepairCost: 6500,
    status: "AVAILABLE",
    dataWipeRequired: false,
    dataWipeCompleted: false,
    recommendedAction: "REPAIR",
    actionConfidence: 0.89,
    aiReasoning: "Optical engine and 3LCD prism intact. 5000 lumens brightness verified. Replacing lamp bulb for ₹6,500 will extend life by 4,000 hours for ITER Civil Seminar Hall (Block 5).",
    serialNumber: "EP-2250U-39912",
    manufacturer: "Epson Corporation",
    modelNumber: "EB-2250U WUXGA",
    specifications: { brightness: "5,000 Lumens", resolution: "1920 x 1200 WUXGA", contrastRatio: "15,000:1", inputs: "Dual HDMI, VGA, LAN" },
    tags: ["ITER Classroom", "High Lumen", "Repairable"],
    createdAt: "2024-08-05T16:20:00Z",
    updatedAt: "2024-08-16T12:10:00Z",
  },
  {
    id: "ast-005",
    assetTag: "ASSET-CSE-219",
    name: "HP LaserJet Enterprise M608dn Heavy-Duty Printer",
    category: "PRINTER",
    condition: "GOOD",
    departmentId: "dept-cse",
    department: MOCK_DEPARTMENTS[0],
    location: { lat: 20.2482, lng: 85.8005, building: "ITER Academic Block 1", floor: "1st Floor", room: "Faculty Printing Center" },
    ageYears: 2.8,
    purchaseDate: "2021-11-05",
    originalPrice: 78000,
    estimatedValue: 38000,
    estimatedRepairCost: 2000,
    status: "AVAILABLE",
    dataWipeRequired: true,
    dataWipeCompleted: true,
    recommendedAction: "REDISTRIBUTE",
    actionConfidence: 0.91,
    aiReasoning: "Total page count 42,000 (well within 275,000 monthly duty cycle). Internal storage wiped and firmware updated to latest patch.",
    serialNumber: "HP-M608-55421",
    manufacturer: "HP Inc.",
    modelNumber: "LaserJet M608dn",
    specifications: { printSpeed: "65 ppm", duplex: "Automatic Duplex", dutyCycle: "275,000 pages/mo", connectivity: "Gigabit Ethernet, USB" },
    tags: ["Heavy Duty", "ITER Block 1", "Firmware Clean"],
    createdAt: "2024-08-08T10:45:00Z",
    updatedAt: "2024-08-17T15:00:00Z",
  },
  {
    id: "ast-006",
    assetTag: "ASSET-RES-501",
    name: "Cisco Catalyst 3850 48-Port PoE+ Managed Switch",
    category: "NETWORKING",
    condition: "EXCELLENT",
    departmentId: "dept-research",
    department: MOCK_DEPARTMENTS[7],
    location: { lat: 20.2475, lng: 85.8024, building: "ITER Advanced Research Center", floor: "3rd Floor", room: "HPC Server Bay 3B" },
    ageYears: 2.0,
    purchaseDate: "2022-06-12",
    originalPrice: 165000,
    estimatedValue: 98000,
    estimatedRepairCost: 0,
    status: "AVAILABLE",
    dataWipeRequired: true,
    dataWipeCompleted: true,
    recommendedAction: "REDISTRIBUTE",
    actionConfidence: 0.97,
    aiReasoning: "StackWise-480 technology and PoE+ budget fully tested. NVRAM sanitization verified with cryptographic hash. Ready for ITER ECE VLSI Lab expansion.",
    serialNumber: "CSCO-3850-48P-99",
    manufacturer: "Cisco Systems",
    modelNumber: "WS-C3850-48P-L",
    specifications: { ports: "48x 10/100/1000 PoE+", poePower: "715W", switchingCapacity: "176 Gbps", stackable: "Up to 9 members" },
    tags: ["Enterprise Networking", "ITER HPC", "High Value"],
    createdAt: "2024-08-03T13:30:00Z",
    updatedAt: "2024-08-14T11:20:00Z",
  },
  {
    id: "ast-007",
    assetTag: "ASSET-MECH-112",
    name: "Godrej Matrix Motorized Height-Adjustable Standing Desk",
    category: "DESK",
    condition: "GOOD",
    departmentId: "dept-mech",
    department: MOCK_DEPARTMENTS[1],
    location: { lat: 20.2468, lng: 85.8018, building: "ITER Mechanical Block (Block 3)", floor: "Ground Floor", room: "CAD/CAM Studio" },
    ageYears: 1.8,
    purchaseDate: "2022-10-01",
    originalPrice: 55000,
    estimatedValue: 36000,
    estimatedRepairCost: 0,
    status: "AVAILABLE",
    dataWipeRequired: false,
    dataWipeCompleted: false,
    recommendedAction: "REUSE",
    actionConfidence: 0.95,
    aiReasoning: "Dual motor smooth lift mechanism operational. Anti-collision sensor functional. 120kg payload capacity verified.",
    serialNumber: "GDRJ-DSK-9921",
    manufacturer: "Godrej Interio",
    modelNumber: "Matrix Pro Dual Motor",
    specifications: { dimensions: "1500 x 750 mm", heightRange: "650 - 1250 mm", motor: "Dual Synchronized Motors", presets: "4 Digital Memory Presets" },
    tags: ["Ergonomic", "ITER Mech", "CAD Ready"],
    createdAt: "2024-08-09T08:15:00Z",
    updatedAt: "2024-08-18T16:40:00Z",
  },
  {
    id: "ast-008",
    assetTag: "ASSET-CIV-033",
    name: "Leica Geosystems Digital Total Station TS07",
    category: "LAB_EQUIPMENT",
    condition: "GOOD",
    departmentId: "dept-civil",
    department: MOCK_DEPARTMENTS[3],
    location: { lat: 20.2460, lng: 85.8008, building: "ITER Civil Engineering Block (Block 5)", floor: "1st Floor", room: "Surveying Store" },
    ageYears: 3.0,
    purchaseDate: "2021-07-20",
    originalPrice: 450000,
    estimatedValue: 260000,
    estimatedRepairCost: 15000,
    status: "AVAILABLE",
    dataWipeRequired: true,
    dataWipeCompleted: true,
    recommendedAction: "REPAIR",
    actionConfidence: 0.92,
    aiReasoning: "Prism angle measurement accuracy tested at 1 arc-second. Laser plummet calibration recommended. Highly valuable for ITER Research Lab geospatial survey projects.",
    serialNumber: "LCA-TS07-10924",
    manufacturer: "Leica Geosystems",
    modelNumber: "FlexLine TS07 1-second",
    specifications: { angleAccuracy: "1 arc second", edmRange: "3,500m with single prism", memory: "2 GB Internal Storage", screen: "3.5 inch Color Touch" },
    tags: ["Surveying", "ITER Lab Grade", "High Capital Asset"],
    createdAt: "2024-08-04T12:00:00Z",
    updatedAt: "2024-08-15T17:30:00Z",
  },
];
